# ===========================================
# Zsh Configuration
# ===========================================

# ------------------------------------
# Environment Secrets (loaded first)
# ------------------------------------

SECRETS_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/.secrets"
if [ -f "$SECRETS_FILE" ]; then
  set -a
  source "$SECRETS_FILE"
  set +a
fi

# ------------------------------------
# Oh My Zsh
# ------------------------------------

export ZSH="$HOME/.oh-my-zsh"

# Theme is overridden by Starship (see bottom of file)
ZSH_THEME="robbyrussell"

# Plugins (keep list short — each one slows startup)
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# ------------------------------------
# Editor
# ------------------------------------

export EDITOR='nvim'

# ------------------------------------
# Key Bindings (tmux-compatible)
# ------------------------------------

bindkey '^[^?' backward-kill-word        # Option+Backspace: delete word
bindkey '^[[1;3D' backward-word          # Option+Left: move word left
bindkey '^[[1;3C' forward-word           # Option+Right: move word right
bindkey '^[[H' beginning-of-line         # Home: start of line
bindkey '^[[F' end-of-line               # End: end of line

# ------------------------------------
# Tool Initialization
# ------------------------------------

# nvm — Node.js version manager
export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
  \. "$NVM_DIR/nvm.sh"
  nvm use default --silent
fi

# yarn & npm global binaries (only if installed)
command -v yarn > /dev/null 2>&1 && export PATH="$PATH:$(yarn global bin)"
command -v npm  > /dev/null 2>&1 && export PATH="$PATH:$(npm bin -g 2>/dev/null)"

# Conda (Anaconda/Miniconda)
if [ -f "/opt/anaconda3/etc/profile.d/conda.sh" ]; then
  . "/opt/anaconda3/etc/profile.d/conda.sh"
elif [ -d "/opt/anaconda3/bin" ]; then
  export PATH="/opt/anaconda3/bin:$PATH"
fi

# Sublime Text CLI (macOS)
[ -d "/Applications/Sublime Text.app" ] && export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"

# Local binaries and custom scripts
export PATH="$HOME/.local/bin:$HOME/bin:$PATH"

# ------------------------------------
# Aliases — static (from dotfiles repo)
# ------------------------------------

if [ -n "$DOTFILES_DIR" ] && [ -d "$DOTFILES_DIR/shell/aliases" ]; then
  for f in "$DOTFILES_DIR/shell/aliases/"*.sh; do
    [ -f "$f" ] && source "$f"
  done
fi

# ------------------------------------
# Aliases — generated (projects, accounts)
# ------------------------------------

if [ -d "$HOME/.aliases.d" ]; then
  for f in "$HOME/.aliases.d/"*.sh; do
    [ -f "$f" ] && source "$f"
  done
fi

# ------------------------------------
# Claude Code — personal account
# ------------------------------------

_CLAUDE_BIN="$HOME/.local/bin/claude"

claude() {
  printf "\e]0;claude - personal\a"
  "$_CLAUDE_BIN" "$@"
}

# Work accounts are generated by install.sh into ~/.aliases.d/

# ------------------------------------
# Prompt — Starship (must be last)
# ------------------------------------

eval "$(starship init zsh)"
