# ===========================================
# Zsh Configuration
# ===========================================

# ------------------------------------
# Environment Secrets (loaded first)
# ------------------------------------

SECRETS_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/.secrets"
if [ -f "$SECRETS_FILE" ]; then
  set -a
  source "$SECRETS_FILE"
  set +a
fi

# ------------------------------------
# Oh My Zsh
# ------------------------------------

export ZSH="$HOME/.oh-my-zsh"

# Theme is overridden by Starship (see bottom of file)
ZSH_THEME="robbyrussell"

# Plugins (keep list short — each one slows startup)
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# ------------------------------------
# Editor
# ------------------------------------

export EDITOR='nvim'

# ------------------------------------
# Key Bindings (tmux-compatible)
# ------------------------------------

bindkey '^[^?' backward-kill-word        # Option+Backspace: delete word
bindkey '^[[1;3D' backward-word          # Option+Left: move word left
bindkey '^[[1;3C' forward-word           # Option+Right: move word right
bindkey '^[[H' beginning-of-line         # Home: start of line
bindkey '^[[F' end-of-line               # End: end of line

# ------------------------------------
# Tool Initialization
# ------------------------------------

# nvm — Node.js version manager
export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
  \. "$NVM_DIR/nvm.sh"
  nvm use default --silent
fi

# yarn & npm global binaries (only if installed)
command -v yarn > /dev/null 2>&1 && export PATH="$PATH:$(cd ~ && yarn global bin)"
command -v npm  > /dev/null 2>&1 && export PATH="$PATH:$(cd ~ && npm bin -g 2>/dev/null)"

# zoxide — smarter cd (powers sesh's directory source)
command -v zoxide > /dev/null 2>&1 && eval "$(zoxide init zsh)"

# Conda (Anaconda/Miniconda)
if [ -f "/opt/anaconda3/etc/profile.d/conda.sh" ]; then
  . "/opt/anaconda3/etc/profile.d/conda.sh"
elif [ -d "/opt/anaconda3/bin" ]; then
  export PATH="/opt/anaconda3/bin:$PATH"
fi

# Sublime Text CLI (macOS)
[ -d "/Applications/Sublime Text.app" ] && export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"

# Local binaries and custom scripts
export PATH="$HOME/.local/bin:$HOME/bin:$PATH"

# Homebrew Ruby gems
if [ -d "/opt/homebrew/lib/ruby/gems/4.0.0/bin" ]; then
  export PATH="/opt/homebrew/lib/ruby/gems/4.0.0/bin:$PATH"
fi

# ------------------------------------
# Aliases — static (from dotfiles repo)
# ------------------------------------

if [ -n "$DOTFILES_DIR" ] && [ -d "$DOTFILES_DIR/shell/aliases" ]; then
  for f in "$DOTFILES_DIR/shell/aliases/"*.sh; do
    [ -f "$f" ] && source "$f"
  done
fi

# ------------------------------------
# Aliases — generated (projects, accounts)
# ------------------------------------

if [ -d "$HOME/.aliases.d" ]; then
  for f in "$HOME/.aliases.d/"*.sh; do
    [ -f "$f" ] && source "$f"
  done
fi

# ------------------------------------
# Aliases — local extras (not tracked, never overwritten)
# Drop any *.sh file into ~/.config/dotfiles/aliases.d/ to have it sourced.
# ------------------------------------

_LOCAL_ALIASES_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/aliases.d"
if [ -d "$_LOCAL_ALIASES_DIR" ]; then
  for f in "$_LOCAL_ALIASES_DIR/"*.sh; do
    [ -f "$f" ] && source "$f"
  done
fi
unset _LOCAL_ALIASES_DIR

# ------------------------------------
# Claude Code
# ------------------------------------

_CLAUDE_BIN="$HOME/.local/bin/claude"

# desc: Launch Claude Code with the personal account (isolated from work proxies)
claude-personal() {
  printf "\e]0;claude - personal\a"
  CLAUDE_CONFIG_DIR="$HOME/.claude-personal" "$_CLAUDE_BIN" "$@"
}

# Routes to CLAUDE_SYMLINK_ACCOUNT (set in .secrets) or claude-personal as fallback
claude() {
  if [ -n "${CLAUDE_SYMLINK_ACCOUNT:-}" ]; then
    "claude-${CLAUDE_SYMLINK_ACCOUNT}" "$@"
  else
    claude-personal "$@"
  fi
}

# Work accounts are generated by install.sh into ~/.aliases.d/

# ------------------------------------
# Cursor — beam at prompt, block during command execution
# ------------------------------------

_set_beam_cursor() { printf '\e[5 q'; }
precmd_functions+=(_set_beam_cursor)

# ------------------------------------
# Prompt — Starship (must be last)
# ------------------------------------

eval "$(starship init zsh)"

return 0
