#!/usr/bin/env bash
# ===========================================
# check.sh — Verify symlinks, generated files, and repo status
# ===========================================
# Checks that all symlinks point to the repo, generated files exist,
# and optionally commits any uncommitted changes.

set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"

# ------------------------------------
# Helpers
# ------------------------------------

info()    { printf "\033[1;34m%s\033[0m\n" "$1"; }
success() { printf "\033[1;32m%s\033[0m\n" "$1"; }
warn()    { printf "\033[1;33m%s\033[0m\n" "$1"; }

check_symlink() {
  local system_path="$1" expected_target="$2"

  if [ ! -e "$system_path" ]; then
    warn "MISSING: $system_path"
    return
  fi

  if [ -L "$system_path" ]; then
    local actual_target
    actual_target="$(readlink "$system_path")"
    if [ "$actual_target" = "$expected_target" ]; then
      success "OK: $system_path → repo"
    else
      warn "WRONG LINK: $system_path → $actual_target (expected $expected_target)"
    fi
  else
    warn "NOT LINKED: $system_path (run install.sh to link)"
  fi
}

# ------------------------------------
# Check symlink health
# ------------------------------------

echo ""
info "=== Checking symlink status ==="
echo ""

check_symlink "$HOME/.zshrc"                    "$DOTFILES_DIR/shell/.zshrc"
check_symlink "$HOME/.tmux.conf"                "$DOTFILES_DIR/tmux/.tmux.conf"
check_symlink "$HOME/.config/ghostty/config"    "$DOTFILES_DIR/terminal/ghostty/config"
check_symlink "$HOME/.config/nvim"              "$DOTFILES_DIR/editor/nvim"
check_symlink "$HOME/.config/starship.toml"     "$DOTFILES_DIR/prompt/starship.toml"
check_symlink "$HOME/.gitignore"                "$DOTFILES_DIR/git/.gitignore"
check_symlink "$HOME/.config/sesh/sesh.toml"    "$DOTFILES_DIR/tools/sesh.toml"
check_symlink "$HOME/.aerospace.toml"           "$DOTFILES_DIR/tools/aerospace.toml"
check_symlink "$HOME/bin/vpn"                   "$DOTFILES_DIR/tools/vpn"

# ------------------------------------
# Check generated files
# ------------------------------------

echo ""
info "=== Generated files (managed by install.sh) ==="
echo ""

if [ -f "$HOME/.gitconfig" ]; then
  if grep -q "# Generated by my-dot-files" "$HOME/.gitconfig" 2>/dev/null; then
    success "OK: ~/.gitconfig (generated)"
  else
    warn "MANUAL: ~/.gitconfig was edited outside install.sh"
  fi
else
  warn "MISSING: ~/.gitconfig (run install.sh)"
fi

if [ -d "$HOME/.aliases.d" ]; then
  count=$(find "$HOME/.aliases.d" -name "*.sh" | wc -l | tr -d ' ')
  success "OK: ~/.aliases.d/ ($count generated files)"
else
  warn "MISSING: ~/.aliases.d/ (run install.sh)"
fi

if [ -f "$HOME/.aliases.d/dotfiles.sh" ]; then
  success "OK: ~/.aliases.d/dotfiles.sh (dotfiles listing command)"
else
  warn "MISSING: ~/.aliases.d/dotfiles.sh (run install.sh)"
fi

# ------------------------------------
# Check repo for uncommitted changes
# ------------------------------------

echo ""
info "=== Repository status ==="
echo ""

cd "$DOTFILES_DIR"

if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  warn "Not a git repository yet. Run: git init && git add -A && git commit -m 'Initial commit'"
  exit 0
fi

if git diff --quiet && git diff --cached --quiet && [ -z "$(git ls-files --others --exclude-standard)" ]; then
  success "No uncommitted changes."
else
  info "Uncommitted changes detected:"
  git status --short
  echo ""
  printf "Commit these changes? [y/N] "
  read -r answer
  if [[ "$answer" =~ ^[Yy]$ ]]; then
    git add -A
    git commit -m "Update dotfiles ($(date +%Y-%m-%d))"
    success "Changes committed!"
  else
    warn "Changes left uncommitted."
  fi
fi
